# fly.toml app configuration file generated for jerma-joke-server on 2023-09-19T23:55:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jerma-logs"
primary_region = "den"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
